name: "S3 Backup Tool"
description: "Home Assistant Addon for S3 Backups compatible with Storj, AWS, MinIO and more"
version: "0.0.1"
slug: "s3_backup_tool"
init: false
startup: services
boot: auto
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
map:
  - backup:rw
hassio_api: true
hassio_role: backup
ingress: true
ingress_port: 8099
panel_icon: mdi:cloud-upload
panel_title: S3 Backup Tool
watchdog: "tcp://[HOST]:[PORT:8099]"

# Standardoptionen (können im Add-on UI überschrieben werden)
options:
  s3_endpoint_url: "https://gateway.storjshare.io"
  s3_region_name: "us-east-1"
  s3_bucket: null
  s3_prefix: "homeassistant/"
  access_key_id: null
  secret_access_key: null
  backup_interval_hours: 24
  full_backup: true
  backup_name_template: "HA Backup {date}"
  verify_ssl: true
  run_on_start: false
  retention_keep_last_s3: 30
  retention_days_s3: 0
  delete_local_after_upload: false
  force_path_style: false
  auto_create_bucket: true
  backup_password: ""
  partial_include_homeassistant: true
  partial_folders: []
  partial_addons: []
  webhook_success_url: ""
  webhook_failure_url: ""
  healthcheck_ping_url: ""
  s3_sse: "NONE"
  s3_sse_kms_key_id: ""
  backup_schedule_cron: ""
  enable_restore_helper: false
  restore_slug: ""
  restore_from_s3_key: ""
  restore_password: ""

# Schema validiert die Optionen
schema:
  s3_endpoint_url: str?
  s3_region_name: str?
  s3_bucket: str
  s3_prefix: str?
  access_key_id: str
  secret_access_key: password
  backup_interval_hours: int
  full_backup: bool?
  backup_name_template: str?
  verify_ssl: bool?
  run_on_start: bool?
  retention_keep_last_s3: int?
  retention_days_s3: int?
  delete_local_after_upload: bool?
  force_path_style: bool?
  auto_create_bucket: bool?
  backup_password: password?
  partial_include_homeassistant: bool?
  partial_folders:
    - str
  partial_addons:
    - str
  webhook_success_url: str?
  webhook_failure_url: str?
  healthcheck_ping_url: str?
  s3_sse: str?
  s3_sse_kms_key_id: str?
  backup_schedule_cron: str?
  enable_restore_helper: bool?
  restore_slug: str?
  restore_from_s3_key: str?
  restore_password: password?
